export const menuData = {
  menu1: [
    {id: 0, menu: 'chicken'},
    {id: 1, menu: 'pizza'},
    {id: 2, menu: 'pasta'},
    {id: 3, menu: 'hotdog'},
    {id: 4, menu: 'jesus'},
    {id: 5, menu: 'burrito'},
    {id: 6, menu: 'john'},
    {id: 7, menu: 'ramen'},
  ],
  menu2: [
    {id: 1, menu: 'chicken'},
    {id: 2, menu: 'chicken'},
    {id: 3, menu: 'chicken'},
    {id: 4, menu: 'chicken'},
    {id: 5, menu: 'chicken'},
    {id: 6, menu: 'chicken'},
    {id: 7, menu: 'chicken'},
    {id: 8, menu: 'chicken'},
  ],
  menu3: [
    {id: 1, menu: 'chicken'},
    {id: 2, menu: 'chicken'},
    {id: 3, menu: 'chicken'},
    {id: 4, menu: 'chicken'},
    {id: 5, menu: 'chicken'},
    {id: 6, menu: 'chicken'},
    {id: 7, menu: 'chicken'},
    {id: 8, menu: 'chicken'},
  ],
};
